apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: influxdb-deployment
    labels:
        app: influxdb
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influxdb
    template:
        metadata:
            name: influxdb-pod
            labels:
                app: influxdb
        spec:
          containers:
          - name: influxdb
            image: influxdb_img
            imagePullPolicy: Never
            ports:
            - containerPort: 8086
              name: influxdb
            livenessProbe:
              exec:
                command:
                - /bin/sh
                - /healthcheck.sh
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 10
              failureThreshold: 3
            volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-persistent-storage
          volumes:
          - name: influxdb-persistent-storage
            persistentVolumeClaim:
              claimName: influxdb-pv-claim

---

apiVersion: v1
kind: Service
metadata:
    name: influxdb-service
    labels:
      app: influxdb
spec:
  selector:
    app: influxdb
  type: ClusterIP
  ports:
  - port: 8086
    name: influxdb
    protocol: TCP
    targetPort: 8086