apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-deployment
    labels:
        app: mysql
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            name: mysql-pod
            labels:
                app: mysql
        spec:
          containers:
          - name: mysql
            image: kmorimot/mysql_img
            imagePullPolicy: Never
            ports:
            - containerPort: 3306
              name: mysql
            livenessProbe:
              exec:
                command:
                - /bin/sh
                - /healthcheck.sh
              initialDelaySeconds: 60
              periodSeconds: 20
              timeoutSeconds: 10
              failureThreshold: 3
            volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-persistent-storage
          volumes:
          - name: mysql-persistent-storage
            persistentVolumeClaim:
              claimName: mysql-pv-claim

---

apiVersion: v1
kind: Service
metadata:
    name: mysql-service
    labels:
      app: mysql
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    name: mysql
    protocol: TCP
    targetPort: 3306

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi