apiVersion: apps/v1
kind: Deployment
metadata:
    name: phpmyadmin-deployment
    labels:
        app: phpmyadmin
spec:
    replicas: 1
    selector:
        matchLabels:
            app: phpmyadmin
    template:
        metadata:
            name: phpmyadmin-pod
            labels:
                app: phpmyadmin
        spec:
          containers:
          - name: phpmyadmin
            image: kmorimot/phpmyadmin_img
            imagePullPolicy: Never
            ports:
            - containerPort: 5000
              name: phpmyadmin
            livenessProbe:
              exec:
                command:
                - /bin/sh
                - /healthcheck.sh
              initialDelaySeconds: 60
              periodSeconds: 20
              timeoutSeconds: 10
              failureThreshold: 3
---

apiVersion: v1
kind: Service
metadata:
    name: phpmyadmin-service
    labels:
      app: phpmyadmin
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: phpmyadmin
  type: LoadBalancer
  ports:
  - port: 5000
    name: phpmyadmin
    protocol: TCP
    targetPort: 5000