apiVersion: apps/v1
kind: Deployment
metadata:
    name: grafana-deployment
    labels:
        app: grafana
spec:
    replicas: 1
    selector:
        matchLabels:
            app: grafana
    template:
        metadata:
            name: grafana-pod
            labels:
                app: grafana
        spec:
          containers:
          - name: grafana
            image: grafana_img
            imagePullPolicy: Never
            ports:
            - containerPort: 3000
              name: grafana

---

apiVersion: v1
kind: Service
metadata:
    name: grafana-service
    labels:
      app: grafana
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: grafana
  type: LoadBalancer
  ports:
  - port: 3000
    name: grafana
    protocol: TCP
    targetPort: 3000