apiVersion: apps/v1
kind: Deployment
metadata:
    name: ftps-deployment
    labels:
        app: ftps
spec:
    replicas: 1
    selector:
        matchLabels:
            app: ftps
    template:
        metadata:
            name: ftps-pod
            labels:
                app: ftps
        spec:
          containers:
          - name: ftps
            image: kmorimot/ftps_img
            imagePullPolicy: Never
            ports:
            - containerPort: 21
              name: ftps
            - containerPort: 30000
              name: pasv-min
            - containerPort: 30001
              name: pasv-max
            livenessProbe:
              exec:
                command:
                - /bin/sh
                - /healthcheck.sh
              initialDelaySeconds: 20
              periodSeconds: 10
              timeoutSeconds: 10
              failureThreshold: 3

---

apiVersion: v1
kind: Service
metadata:
    name: ftps-service
    labels:
      app: ftps
    annotations:
      metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - port: 21
    name: ftps
    protocol: TCP
    targetPort: 21
  - port: 30000
    name: pasv-min
    protocol: TCP
    targetPort: 30000
  - port: 30001
    name: pasv-max
    protocol: TCP
    targetPort: 30001